name: openclaw-v0
region: syd

# V0 scaffold for DigitalOcean App Platform.
# - Use as a Worker (no inbound HTTP required for Telegram long-polling).
# - Instance size pinned to 1cpu/2gb.
#
# Deploy from a pre-built image in GHCR (GitHub Container Registry).
# Build/push via CI (see .github/workflows/ghcr-build-push.yml), then App Platform pulls.
# GHCR images are public — no registry credentials needed.

workers:
  - name: openclaw-agent
    image:
      registry_type: DOCKER_HUB
      registry: ghcr.io
      repository: bikramkgupta/openclaw-agent
      tag: latest
    instance_size_slug: apps-s-1vcpu-2gb
    instance_count: 1
    envs:
      # Agent identity
      - key: AGENT_ID
        scope: RUN_TIME
        value: "agent-cattle-mode"
      - key: AGENT_NAME
        scope: RUN_TIME
        value: "OpenClaw Cattle Mode"

      # Telegram (v0: required)
      - key: TELEGRAM_BOT_TOKEN
        scope: RUN_TIME
        type: SECRET
      - key: TELEGRAM_ALLOWFROM
        scope: RUN_TIME
        # Comma-separated Telegram user IDs. If empty: pairing mode.
        value: "6944791786"

      # Providers
      - key: GRADIENT_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: AGENT_DEFAULT_MODEL
        scope: RUN_TIME
        value: ""

      # Node/V8 memory:
      # App Platform may run Node with a low default heap limit in containers.
      # Force a higher heap ceiling (in MB) to prevent ~512MB OOMs.
      - key: NODE_OPTIONS
        scope: RUN_TIME
        value: "--max-old-space-size=1536"

      # Gateway auth token (required)
      - key: OPENCLAW_GATEWAY_TOKEN
        scope: RUN_TIME
        type: SECRET

      # Object store (DigitalOcean Spaces)
      - key: SPACES_BUCKET
        scope: RUN_TIME
        value: "openclaw-cattle-mode-syd1"
      - key: SPACES_REGION
        scope: RUN_TIME
        value: "syd1"
      - key: SPACES_ACCESS_KEY_ID
        scope: RUN_TIME
        type: SECRET
      - key: SPACES_SECRET_ACCESS_KEY
        scope: RUN_TIME
        type: SECRET
