name: openclaw-v0
region: syd

# V0 scaffold for DigitalOcean App Platform.
# - Use as a Worker (no inbound HTTP required for Telegram long-polling).
# - Instance size pinned to 1cpu/1gb as requested.
#
# Deploy from a pre-built image in DOCR (DigitalOcean Container Registry).
# Build/push via CI (see .github/workflows/build-push.yml), then App Platform pulls.

workers:
  - name: openclaw-agent
    image:
      registry_type: DOCR
      # Registry name: "openclaw" (change if your DOCR registry differs)
      # Full image: registry.digitalocean.com/openclaw/openclaw-agent:latest
      repository: openclaw/openclaw-agent
      tag: latest
    instance_size_slug: apps-s-1vcpu-2gb
    instance_count: 1
    envs:
      # Agent identity
      - key: AGENT_ID
        scope: RUN_TIME
        value: "agent-dev"
      - key: AGENT_NAME
        scope: RUN_TIME
        value: "OpenClaw Dev Agent"

      # Telegram (v0: required)
      - key: TELEGRAM_BOT_TOKEN
        scope: RUN_TIME
        type: SECRET
      - key: TELEGRAM_ALLOWFROM
        scope: RUN_TIME
        # Comma-separated Telegram user IDs. If empty: pairing mode.
        value: "6944791786"

      # Providers
      - key: GRADIENT_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: OPENAI_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: ANTHROPIC_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: AGENT_DEFAULT_MODEL
        scope: RUN_TIME
        value: ""

      # Gateway auth token (required)
      - key: OPENCLAW_GATEWAY_TOKEN
        scope: RUN_TIME
        type: SECRET

      # Object store (DigitalOcean Spaces)
      - key: SPACES_BUCKET
        scope: RUN_TIME
        value: "openclaw-cattle-mode-syd1"
      - key: SPACES_REGION
        scope: RUN_TIME
        value: "syd1"
      - key: SPACES_ACCESS_KEY_ID
        scope: RUN_TIME
        type: SECRET
      - key: SPACES_SECRET_ACCESS_KEY
        scope: RUN_TIME
        type: SECRET
