name: openclaw-v0
region: syd

# V0 scaffold for DigitalOcean App Platform.
# - Use as a Worker (no inbound HTTP required for Telegram long-polling).
# - Instance size pinned to 1cpu/1gb as requested.
#
# NOTE: This file is a scaffold only; you are not deploying yet.

workers:
  - name: openclaw-agent
    # Replace this with your DOCR repository once you publish the image.
    image:
      registry_type: DOCR
      repository: openclaw/openclaw-agent
      tag: latest
    instance_size_slug: apps-s-1vcpu-1gb-fixed
    instance_count: 1
    envs:
      # Agent identity
      - key: AGENT_ID
        scope: RUN_TIME
        value: "agent-dev"
      - key: AGENT_NAME
        scope: RUN_TIME
        value: "OpenClaw Dev Agent"

      # Telegram (v0: required)
      - key: TELEGRAM_BOT_TOKEN
        scope: RUN_TIME
        type: SECRET
      - key: TELEGRAM_ALLOWFROM
        scope: RUN_TIME
        value: ""

      # Providers
      - key: GRADIENT_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: OPENAI_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: ANTHROPIC_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: AGENT_DEFAULT_MODEL
        scope: RUN_TIME
        value: ""

      # Gateway auth token (required)
      - key: OPENCLAW_GATEWAY_TOKEN
        scope: RUN_TIME
        type: SECRET

      # Object store (DigitalOcean Spaces)
      - key: SPACES_BUCKET
        scope: RUN_TIME
        value: "REPLACE_ME_BUCKET"
      - key: SPACES_REGION
        scope: RUN_TIME
        value: "REPLACE_ME_REGION"
      - key: SPACES_ACCESS_KEY_ID
        scope: RUN_TIME
        type: SECRET
      - key: SPACES_SECRET_ACCESS_KEY
        scope: RUN_TIME
        type: SECRET
