name: openclaw-v0
region: syd

# V0 scaffold for DigitalOcean App Platform.
# - Use as a Worker (no inbound HTTP required for Telegram long-polling).
# - Instance size pinned to 1cpu/2gb.
#
# Deploy from a pre-built image in GHCR (GitHub Container Registry).
# Build/push via CI (see .github/workflows/ghcr-build-push.yml), then App Platform pulls.
# registry_type: GHCR handles GHCR's token-exchange auth automatically.
#
# Env vars use ${VAR} placeholders — substituted from .env.remote by scripts/deploy.sh.
# Do NOT deploy this file directly; use: bash scripts/deploy.sh

workers:
  - name: openclaw-agent
    image:
      registry_type: GHCR
      registry: ghcr.io
      repository: bikramkgupta/openclaw-agent
      tag: ${IMAGE_TAG}
    instance_size_slug: apps-s-1vcpu-2gb
    instance_count: 1
    envs:
      # Agent identity
      - key: AGENT_ID
        scope: RUN_TIME
        value: "${AGENT_ID}"
      - key: AGENT_NAME
        scope: RUN_TIME
        value: "${AGENT_NAME}"

      # Telegram
      - key: TELEGRAM_BOT_TOKEN
        scope: RUN_TIME
        value: "${TELEGRAM_BOT_TOKEN}"
      - key: TELEGRAM_ALLOWFROM
        scope: RUN_TIME
        value: "${TELEGRAM_ALLOWFROM}"

      # Providers
      - key: GRADIENT_API_KEY
        scope: RUN_TIME
        value: "${GRADIENT_API_KEY}"
      - key: AGENT_DEFAULT_MODEL
        scope: RUN_TIME
        value: "${AGENT_DEFAULT_MODEL}"

      # Node/V8 memory
      - key: NODE_OPTIONS
        scope: RUN_TIME
        value: "${NODE_OPTIONS}"

      # Gateway auth token
      - key: OPENCLAW_GATEWAY_TOKEN
        scope: RUN_TIME
        value: "${OPENCLAW_GATEWAY_TOKEN}"

      # Object store (DigitalOcean Spaces)
      - key: SPACES_BUCKET
        scope: RUN_TIME
        value: "${SPACES_BUCKET}"
      - key: SPACES_REGION
        scope: RUN_TIME
        value: "${SPACES_REGION}"
      - key: SPACES_ACCESS_KEY_ID
        scope: RUN_TIME
        value: "${SPACES_ACCESS_KEY_ID}"
      - key: SPACES_SECRET_ACCESS_KEY
        scope: RUN_TIME
        value: "${SPACES_SECRET_ACCESS_KEY}"
